version: "3"
services:
    docker-app:
        build: 
            context: .
            dockerfile: ./docker-app/Dockerfile
        container_name: multi_app
        volumes:
            - ./:/home/basavyr