version: "3"
services:
    test-apps:
        build: 
            context: .
            dockerfile: ./docker-test/Dockerfile
        container_name: test_apps
        volumes:
            - ./:/home/basavyr
    run-apps:
        build: 
            context: .
            dockerfile: ./docker-app/Dockerfile
        container_name: run_apps
        volumes:
            - ./:/home/basavyr